### PR TITLE
Fix decoupledhelper use due to error message

### PR DESCRIPTION
**Pull request by sagark**
This is for the Rocket Chip bump to master, but doesn't break old versions. Ready to merge if you're fine with this @davidbiancolin

### CODE REVIEW

**Comment by aswaterman** [comment]
Wow that's ugly lol

**Comment by sagark** [comment]
https://github.com/freechipsproject/rocket-chip/pull/1645  :)

**Comment by aswaterman** [comment]
Ack.  I've merged https://github.com/freechipsproject/rocket-chip/pull/1645

**Comment by davidbiancolin** [comment]
I thought that was the old RC PR -- thanks @mehnadnerd.

**Pull request merged**
