### PR TITLE
Endpointed Print Synthesis

### PR DESCRIPTION
**Pull request by davidbiancolin**
This PR reenables print synthesis. The FireSim PR will have greater detail. 

It has a few enhancements:
- null token compression
- token packing for narrow prints
- serialization for wide prints
- printf formatting matches verilator output (except for a few format types)

Todos:
- [x] PR TopWiring changes to FIRRTL
- [x] Performance tuning on F1
- [x] Second midasexample that packs multiple prints into a single DMA beat

### CODE REVIEW

**Comment by davidbiancolin** [comment]
@sagark @alonamid  This is ready to review

**Comment by alonamid** [comment]
@a0u , are there still issues with prints in unexpected places?

**Comment by a0u** [comment]
@alonamid: Yes, this happens not only with Hwacha (both 1-lane and 2-lane designs) but also with the rocket commit log, without performing any modifications for QoR like pipelining the print arguments.  The cycle counter is not always increasing monotonically with each log statement, which suggests some lines are corrupted.

**Comment by davidbiancolin** [comment]
Since this is an optional feature, I'm going to merge this PR and then work on bug fixes directly on dev.

**Pull request merged**
